#!/bin/bash
#
# RFChain HUD - MySQL Database Setup Script
# This script creates the MySQL database and user for local deployment
#
# Usage: ./setup-mysql.sh
#
# Requirements:
#   - MySQL Server installed (sudo apt install mysql-server)
#   - sudo privileges
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          RFChain HUD - MySQL Database Setup                  ║"
echo "║          Forensic Signal Intelligence System                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Default values
DB_NAME="${DB_NAME:-rfchain_hud}"
DB_USER="${DB_USER:-rfchain}"
DB_HOST="${DB_HOST:-localhost}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Check if running as root (not recommended)
if [ "$EUID" -eq 0 ]; then
    echo -e "${YELLOW}[WARNING] Running as root. Consider running as a regular user with sudo access.${NC}"
fi

# Check for MySQL installation
echo -e "${CYAN}[1/5] Checking MySQL installation...${NC}"
if ! command -v mysql &> /dev/null; then
    echo -e "${YELLOW}MySQL not found. Installing...${NC}"
    sudo apt update
    sudo apt install -y mysql-server
    sudo systemctl start mysql
    sudo systemctl enable mysql
    echo -e "${GREEN}✓ MySQL installed and started${NC}"
else
    echo -e "${GREEN}✓ MySQL is installed${NC}"
    
    # Check if MySQL service is running
    if ! systemctl is-active --quiet mysql; then
        echo -e "${YELLOW}Starting MySQL service...${NC}"
        sudo systemctl start mysql
    fi
fi

# Prompt for password
echo ""
echo -e "${YELLOW}Enter a password for MySQL user '${DB_USER}':${NC}"
echo -e "${CYAN}(This password will be used in your .env.local file)${NC}"
read -s DB_PASS
echo

if [ -z "$DB_PASS" ]; then
    echo -e "${RED}[ERROR] Password cannot be empty${NC}"
    exit 1
fi

# Confirm password
echo -e "${YELLOW}Confirm password:${NC}"
read -s DB_PASS_CONFIRM
echo

if [ "$DB_PASS" != "$DB_PASS_CONFIRM" ]; then
    echo -e "${RED}[ERROR] Passwords do not match${NC}"
    exit 1
fi

echo -e "${CYAN}[2/5] Creating database and user...${NC}"

# Create database and user
sudo mysql -e "
    CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASS}';
    GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'${DB_HOST}';
    FLUSH PRIVILEGES;
" 2>/dev/null || {
    echo -e "${RED}[ERROR] Failed to create database. Trying alternative method...${NC}"
    # Try with password prompt
    sudo mysql -u root -p -e "
        CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASS}';
        GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'${DB_HOST}';
        FLUSH PRIVILEGES;
    "
}

echo -e "${GREEN}✓ Database '${DB_NAME}' and user '${DB_USER}' created${NC}"

echo -e "${CYAN}[3/5] Testing connection...${NC}"
if mysql -u"${DB_USER}" -p"${DB_PASS}" -h"${DB_HOST}" -e "USE ${DB_NAME}; SELECT 1;" &> /dev/null; then
    echo -e "${GREEN}✓ Connection successful${NC}"
else
    echo -e "${RED}[ERROR] Failed to connect to database${NC}"
    echo -e "${YELLOW}Please check your MySQL configuration and try again.${NC}"
    exit 1
fi

echo -e "${CYAN}[4/5] Generating connection string...${NC}"
CONNECTION_STRING="mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}"

# Generate JWT secret
JWT_SECRET=$(openssl rand -base64 32)

echo -e "${CYAN}[5/5] Creating .env.local file...${NC}"

# Check if .env.local already exists
if [ -f "$PROJECT_DIR/.env.local" ]; then
    echo -e "${YELLOW}[WARNING] .env.local already exists.${NC}"
    echo -e "${YELLOW}Creating backup as .env.local.backup${NC}"
    cp "$PROJECT_DIR/.env.local" "$PROJECT_DIR/.env.local.backup"
fi

# Create .env.local with the database connection
cat > "$PROJECT_DIR/.env.local" << EOF
# ============================================================================
# RFChain HUD - Self-Hosted Configuration
# Generated by setup-mysql.sh on $(date)
# ============================================================================

# Database
DATABASE_URL="${CONNECTION_STRING}"

# Server
PORT=3007
NODE_ENV=production
HOST=0.0.0.0

# Authentication
JWT_SECRET="${JWT_SECRET}"

# Python (UPDATE THESE PATHS FOR YOUR SYSTEM)
PYTHON_PATH=/home/$(whoami)/miniconda3/envs/rfchain-hud/bin/python
ANALYSIS_SCRIPT_PATH=/home/$(whoami)/RFChain/analyze_signal_v2.2.2_forensic.py

# File Storage
UPLOAD_DIR=./uploads
ANALYSIS_OUTPUT_DIR=./analysis_output
AUDIO_DIR=./audio_uploads

# GPU
GPU_ENABLED=true
CUDA_VISIBLE_DEVICES=0

# LLM (Uncomment ONE option)
# Option 1: Local Ollama (recommended for forensic use)
# OLLAMA_HOST=http://localhost:11434
# OLLAMA_MODEL=llama3

# Option 2: Anthropic Claude
# ANTHROPIC_API_KEY=your-api-key-here

# Logging
LOG_LEVEL=info
LOG_FILE=./logs/rfchain-hud.log
EOF

echo -e "${GREEN}✓ Created .env.local${NC}"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Database Setup Complete!                        ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Database Connection String:${NC}"
echo -e "${YELLOW}${CONNECTION_STRING}${NC}"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo -e "  1. Edit ${YELLOW}.env.local${NC} to update Python paths for your system"
echo -e "  2. Run database migration: ${YELLOW}cd $PROJECT_DIR && pnpm db:push${NC}"
echo -e "  3. Build the application: ${YELLOW}pnpm build${NC}"
echo -e "  4. Start the server: ${YELLOW}./deploy/start.sh${NC}"
echo ""
echo -e "${CYAN}First-time setup:${NC}"
echo -e "  - The first user to register will become the admin"
echo -e "  - Access the app at: ${GREEN}http://localhost:3007${NC}"
echo ""
